### ISSUE TITLE
is this a fork of colorette?

### ISSUE THREAD

**Issue by franciscoandres** [ai/nanocolors#1]
Is this a fork of colorette by Jorge Bucaran? Just asking...

**Comment by ai** [comment]
Yeap. Recent [`colorette` 2.x](https://github.com/jorgebucaran/colorette/issues/70) release made it impossible to use this tool (because of extra call on every use case).

Also I optimized loading time and add browsers support.

**Comment by dospolov** [comment]
@ai thank you for your work. I personally support your approach of forking and extending original repo - that is what open source all about

**Comment by kibertoad** [comment]
Btw, the API change in 2x was reversed and new API is optional and opt-in, old API works as-was.

**Comment by ai** [comment]
@kibertoad I still see the big problems in `colorette` maintaince:

1. Broken SemVer by adding `--color` and `--no-color` arguments support in batch `2.0.13` release.
2. Copyright problems of cloning `picocolors` improvements without mentioning origin project.

Allow me to be open. Adding you to maintainers didn’t solve (yet) impulsive behavior. It is still impossible to use `colorette` in big projects,

**Comment by ai** [comment]
@kibertoad my current plan is to close `nanocolors` in flavor of [`picocolors`](https://github.com/alexeyraspopov/picocolors).

I think that the only way to close the conflict is to give place for new generation of developers. We (`colorette` and `nanocolors`) are both corrupted. `picocolors` maintainer shows, in contrast, very clever optimization with long-term disitions.

**Comment by kibertoad** [comment]
1. It's not pragmatically a SemVer breaking change, at most it is a new feature, I don't imagine anything getting broken by this in real production, and rolling it back at this point would be complex and expensive. However, Pull Request review policy was discussed and enacted after this particular incident, this will not happen again;
2. This is not true: https://github.com/jorgebucaran/colorette/releases/tag/2.0.14 references origin project directly, and Jorge is currently thinking of how to amend readme file to accommodate Alexey's wishes;
3. Again, this was unfortunate, but will not happen again, because now such changes and versioning are discussed up-front. We are coordinating releases together now;
4. If I remember the whole story correctly, `small performance improvements` ended up not doing anything helpful and were dropped, hence they are not retroactively mentioned anywhere. If you feel that there is any meaningful part of nanocolors still present in colorette, we would be more than happy to credit you for it in a way that you find appropriate. Let me know if that is the case.

I disagree. Personally I'm seeing huge difference in how Colorette development is happening now. Hopefully it will be more visible in the nearby future and we could dispell your scepticism :).

I also don't see `colorette` as corrupted or wrong. It is a great library that works great. `picocolors` is a very exciting project with a really talented developer, and I hope it prospers. `nanocolors` seems rather redundant for me at this point, but in which direction you decide to take it, if any, is obviously up to you :)

**Comment by ai** [comment]
> It's not pragmatically a SemVer breaking change, at most it is a new feature, I don't imagine anything getting broken by this in real production.

I, as a `colorette` user, disagree. You could have a different opinion.

For my projects, it is broken promises. I can’t trust the utility package with this type of changes in patch releases.

But I do not force you to have my opinion. I just, personally, prefer to use a different type of SemVer compatibility.

> This is not true: https://github.com/jorgebucaran/colorette/releases/tag/2.0.14 references origin project directly, and Jorge is currently thinking of how to amend readme file to accommodate Alexey's wishes;

`picocolors` doesn’t mention directly in `README.md`. Even in ChangeLog Jorge mentiones commit, not a project by name.

For me, it is a clear image that he tries to hide a competitor.

In contrast, `picocolors` mentions `colorette` with a direct link.

For me, Jorge thinking instead of adding a link imminently after the ask is a not fair game.

> This was unfortunate, but will not happen again, because now such changes and versioning are discussed up-front. We are coordinating releases together now. Rolling it back at this point would be complex and expensive. However, Pull Request review policy was discussed and enacted after this particular incident, this will not happen again;

After `2.0.13` I disagree that “will not happen again”.

>  If you feel that there is any meaningful part of nanocolors still present in colorette, we would be more than happy to credit you for it in a way that you find appropriate

Yes, please. With direct link to `nanocolors` and any type of mentions including `our collaboration` or `Prior Art`.

**Comment by kibertoad** [comment]
I've just added link to picocolors in release notes. I'm not sure that a single small optimization is significant enough to be mentioned in readme, but I'm open to be convinced otherwise. Changelog seems more appropriate because it is focused on that particular specific change. It can't be fairly said that Colorette design overall is heavily influenced by picocolors.

> Yes, please. With direct link to nanocolors and any type of mentions including our collaboration or Prior Art.

Can you please help me by listing which particular parts of nanocolors are currently still used in colorette? The one that I am aware of is https://github.com/jorgebucaran/colorette/commit/b1d82b9a9204bdac19b6306c2426a179f4cd6c6b, and from my understanding it was later reversed because it was not actually helping. If there is anything else still left, please point at it, and I would be happy to work out with Jorge path to properly attribute it.

**Comment by ai** [comment]
> I've just added link to picocolors in release notes.

Could you please added `picocolors` mention and link to `README.md`. Current `Acknowledgements` content is misleading as `picocolors` told.

> I'm not sure that a single small optimization is significant enough to be mentioned in readme, but I'm open to be convinced otherwise. 

Do not copy, it is not significant enough.

`picocolors` mentions `colorette` in `README.md` with a direct link, for example.

> Can you please help me by listing which particular parts of nanocolors are currently still used in colorette? 

It is `s ||` https://github.com/jorgebucaran/colorette/blob/main/index.js#L38

Jorge firstly copied `!s &&` from `nanocolors` which causes 2x performance boost. In https://github.com/jorgebucaran/colorette/commit/d1ff3a7048416788c9ca89f3c27f9d11a24ebb9d in was not removed, but replaced with reverse check to hide fact of copying (as I assume according to [this discussion](https://github.com/jorgebucaran/colorette/issues/78#issuecomment-927275427)).

**Comment by kibertoad** [comment]
Sure, we'll discuss with Jorge and figure out how and where we can attribute all of this.

**Comment by kibertoad** [comment]
@jorgebucaran Please read discussion above and let's plan tomorrow :)

**Comment by jorgebucaran** [comment]
Absolutely. It was an oversight to not include a link back to picocolors in our acknowledgments. [I've rectified this now](https://github.com/jorgebucaran/colorette/#acknowledgements). 👍
