### ISSUE TITLE
Stolen library and fame

### ISSUE THREAD

**Issue by StoneCypher** [ai/nanocolors#22]
You went way out of your way to look like you invented nanocolors, when it's actually someone else's work whose background you intentionally hid

You should destroy this repository and apologize.  All those users and that money belong to him, and you know it. 

All of your work is now suspect.

I have removed your work from every repo I have control over, and I am encouraging everyone I know to do the same.

You are an unrepentant plagiarist demanding recognition from your victim.

**Comment by ai** [comment]
Why do you think that I am inventor of everything if `README.md` contains clear ark about fork (origin author is also mentioned in `COPYRIGHT` file and GitHub history)?

>Started as a fork
> of [**@jorgebucaran**](https://github.com/jorgebucaran/)’s
> [`colorette`](https://github.com/jorgebucaran/colorette) with hacks
> from [**@lukeed**](https://github.com/lukeed/)’s
> [`kleur`](https://github.com/lukeed/kleur).
> See [changes](https://github.com/ai/nanocolors/wiki/Colorette-Changes)
> between Nano Colors and `colorette`.

Here is a pretty clear explanation why `colorette` maintaining mistakes force me to fork the project (I used it before for a year in all my projects, promoted and send PRs): https://github.com/ai/nanocolors/wiki/Colorette-Changes

**Comment by ai** [comment]
Also note, that `colorette` mention (in docs and `LICENSE`) was added to docs before any Twitter thread when `colorette`’s author asked me. We even agreed on text.

**Comment by StoneCypher** [comment]
The removal of the history is still visible, can only have been intentional, and has no non-plagiarism explanation

**Comment by StoneCypher** [comment]
Forking is fine. I've done it many times myself, and am about to do it again.

You misrepresented what parts of this you wrote, and had to be reached out to to reestablish the credit you're now pretending that you gave all along

Your explanations don't change how this looks

**Comment by ai** [comment]
I explain git history removal in my thread:
https://twitter.com/sitnikcode/status/1441827379454746637

(The project was created from the begging because I planned to mix Colorette and kleur and do not do just Colorette fork.)

**Comment by Mitsunee** [comment]
As I've previously stated on twitter, I clicked on this repository within minutes of @ai sharing it on twitter and the first thing I saw is the previously mentioned paragraph about this package being a fork of colorette with "with hacks from kleur" (and thus not a pure 100% fork of just one project).

This was before all of this entirely unprofessional drama shitfest started and judging by everything I read on twitter and the PR in the babel repository I seem to have gotten the intended impression from the readme, which certain other people seemingly didn't.

**Comment by ai** [comment]
Here is proof that  the first Colorette and kleur mention was added before the Twitter thread (5 days ago)

https://www.npmjs.com/package/nanocolors/v/0.1.2

**Comment by StoneCypher** [comment]
Imagine thinking that you can explain away removing the history of someone else's work and putting it under your own name

The more you try to explain this, the worse it looks

**Comment by neoromantique** [comment]
> Here is proof that  the first Colorette and kleur mention was added before the Twitter thread (5 days ago)
> 
> 
> 
> https://www.npmjs.com/package/nanocolors/v/0.1.2

API inspiration and copying 99% of the code aren't really the same thing.

**Comment by neoromantique** [comment]
Personally after reading through this full shitfest of twitter, PRs etc (I don't know why) I think that this isn't some malicious thing to overtake a library, but rather simple chain of misunderstandings, which as often happens in open source lead to a personal drama.

Both sides initial reactions are justified, but I feel that @ai, began slandering @jorgebucaran a bit by trying to defend his decision, despite the pushback.

That's the ugly part, instead of being productive and finding some common ground through discussion this is just a rabbit hole into more drama.

**Comment by StoneCypher** [comment]
I have a hard time understanding how you can think removing a code history is anything other than malicious, especially given how obvious it is that the original author does not want this

"but I put it in the Readme, then took credit for every line of work and demanded that the original author credit me, and publicly criticized him over it"

He's had and declined many chances to make right

**Comment by neoromantique** [comment]
> I have a hard time understanding how you can think removing a code history is anything other than malicious, especially given how obvious it is that the original author does not want this
> 
> 
> 
> "but I put it in the Readme, then took credit for every line of work and demanded that the original author credit me, and publicly criticized him over it"
> 
> 
> 
> He's had and declined many chances to make right 

Benefit of the doubt, and especially considering different mentalities it doesn't seem as bad as it initially did. Hopefully they'll find the compromise one way or another, after the storm settles.

**Comment by StoneCypher** [comment]
There's no benefit of the doubt to be given. He's caught red handed, and unrepentant. He continues to attempt to publicly shame the victim.

If you need to make apologies for him, please don't do it on my ticket. I know what plagiarism feels like and I don't want to watch you apologize for it. Thank you

**Comment by ai** [comment]
> API inspiration and copying 99% of the code aren't really the same thing.

Tests, types, benchmarks, browser support, project’s configs was written again.

I took one file and mixed it with ideas from `kleur` and added  my loading time optimizations.

But of course I understand that `index.js` is the most important part and changed mention when another user send PR.

When another user suggested way to copy Colorette’s history for this specific file, I did it as well.

**Comment by StoneCypher** [comment]
You removed the history and put your name on everything he wrote, line by line

Every explanation you give ignores what he's angry about and what people are saying to you

"But I rewrote some tests?"

Stop. Lines of code someone else wrote had your name on them because you went to extra effort to remove the author

You can't explain your way out

**Comment by ai** [comment]
I am explaining the historical context of the fork.

I agree that I should mentioned Colorette author in better way and I should kept for history of `index.js`. and this is exactly what I fixed.

You can blame for mistakes of the past. But I fixed them not because of the Twitter thread, but because of advice and help from other people.

Can I remove this fork? Not, I created a fork because I lost trust in Colorette maintenance in `2.x` release.

**Comment by StoneCypher** [comment]
Stop making yourself out as a victim.

**Comment by Mitsunee** [comment]
I was going to not participate in whatever this is (discussion? idk?), but this clearly isn't going anywhere, so I might as well vent.

> You removed the history and put your name on everything he wrote, line by line
> 
> [...]
> 
> Stop. Lines of code someone else wrote had your name on them because you went to extra effort to remove the author

The history of this repository has been rebased on top of colorette's history as a compromise already. Restoring the line-by-line author attribution would require further rewriting of history. Not to mention that none of the code from kleur will be attributed correctly at that point either. Adding that too would mess up the commit history even more, in the end making it even less clear who did what. Is that what you want? More confusion? Or the possibility of even more mistakes because rebase is very easy to mess up to begin with?

Nevermind that nothing that was done here is a breach of the license under which the code of colorette was published. Can we just stop with this stupid drama and fingerpointing back and fourth and come to some sort of agreement and then leave it at that? There are people trying to use the libraries in question who are currently just sitting here waiting for this dumpsterfire to get put out so we can know who will maintain what package with what API in the future or not.

Babel have already stated that they will not take any action on sitnik's pull request for the next two weeks, seemingly because they also don't know how to parse this failure to stay civil from all parties involved (although the maintainers of chalk tried their best to be as professional as possible about it while still stating their opinion, but oh well...).

**Comment by StoneCypher** [comment]
Putting their name back on their own work is in no sense a compromise

It's not even restitution

**Comment by ai** [comment]
@StoneCypher issues was not created for the purpose of hurting maintainers (this is what @StoneCypher is doing). This is why I am closing it.

Issue was created to ask a question (it is better to use Discussions), asking for changes or reporting a problem.

If you want to mention Colorette in any other way, feel free to open another issue.

If you want to close the project, we need firstly to solve initial reasons why the fork was created (Colorette impulsive changes). I can’t moved to `kleur` because it is not so minimalistic. I can’t move to `felt-pen` because of the changes in color support detection. I can move to `chalk` because of the lack of performance passion. If you know another minimalistic project, feel free to open another issue.

**Comment by StoneCypher** [comment]
None of this would have been a problem if you hadn't removed credit

Your ongoing explanations and misrepresentation of yourself as an innovator or a victim are eye opening

**Comment by StoneCypher** [comment]
I do know many other minimalist projects, several moreso than this

I cannot in good conscience expose them to you
